export const SIGN_IN_USER_SUBMIT = 'SIGN_IN_USER_SUBMIT';

export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';

export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';

export const SIGN_IN_USER_FAIL = 'SIGN_IN_USER_FAIL';

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
