export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST'

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST'

export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'

export const UNAUTH_USER = 'UNAUTH_USER'
